### ISSUE TITLE
Pulsir 4?

### ISSUE THREAD

**Issue by intemperies** [pulsir/pulsir#48]
I think Pulsir 4 would be great idea, since there are several issues and several suggestions:

Issues:
- At the moment, homepage is really laggy, I guess because of large image size.
- It doesn't force users to use HTTPS from .htaccess
- It isn't written in any framework, so the code isn't that easy to manage.
- Url's aren't pretty, still .php, no rules in .htaccess

Suggestions:
- Making a new project from scratch and recode every functionality
- Making it with our custom framework would be even better (I started making my own framework so it could be based on that)

**Comment by intemperies** [comment]
Also a better frond-end would be great.

**Comment by iwebhub** [comment]
Pulsir 3 is incredibly unmaintainable which is why I stopped bothering a while ago.

I'd love Pulsir to become something different, something _usable_ and _maintainable_ and something people actually use -- however, this would require a massive [undertaking](http://arrow.wikia.com/wiki/The_Undertaking_(event)).

If you're interested in working on Pulsir 4, I'd love to help in any way that I can: by coding, hosting, whatever. However, this isn't a small task and we'd need more contributors. Hopefully we can gather them.

**Comment by intemperies** [comment]
I can dedicate myself while I'm on holidays, also if you can, create a new repository named 'pulsir4'.

**Comment by iwebhub** [comment]
That would be great. As it's summer break for me as well, I can contribute to your efforts.

I'll open a new repository.

**Comment by iwebhub** [comment]
All work on Pulsir 4 should be continued in pulsir/pulsir4.
